apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-ui
  namespace: rag-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rag-ui
  template:
    metadata:
      labels:
        app: rag-ui
    spec:
      containers:
        - name: rag-ui
          image: docker.io/aryansr/rag-app-react-gui:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rag-ui
  namespace: rag-app
spec:
  type: LoadBalancer
  selector:
    app: rag-ui
  ports:
    - port: 80
      targetPort: 80
