pipeline {

    agent any

    environment {

        IMAGE_TAG = "${BUILD_NUMBER}"

        IMAGE_NAME = "docker.io/aryansr/rag-microservice-app_ingestor"

        YAML_FILE = "applications/rag-app/manifests/ingestor.yaml"
    }

    stages {

        stage('Checkout Repo') {

            steps {

                git branch: 'main',
                    credentialsId: 'github-creds',
                    url: 'https://github.com/networknuts/k8s-ai-rag-app.git'
            }
        }

        stage('Build and Push Docker Image') {

            steps {

                script {

                    dir('applications/rag-app/ingestor-service') {

                        def dockerImage = docker.build(
                            "${IMAGE_NAME}:${IMAGE_TAG}",
                            "."
                        )

                        docker.withRegistry('', 'dockerhub-credentials') {

                            dockerImage.push("${IMAGE_TAG}")
                        }
                    }
                }
            }
        }

        stage('Update Kubernetes YAML') {
        
            steps {
        
                sh """
        
                yq -y -i '
                .spec.template.spec.containers[0].image =
                "${IMAGE_NAME}:${IMAGE_TAG}"
                ' ${YAML_FILE}
        
                """
            }
        }

        stage('Commit and Push Changes') {

            steps {

                withCredentials([
                    usernamePassword(
                        credentialsId: 'github-creds',
                        usernameVariable: 'GIT_USER',
                        passwordVariable: 'GIT_PASS'
                    )
                ]) {

                    sh """

                    git config user.email "jenkins@networknuts.com"
                    git config user.name "jenkins"

                    git add ${YAML_FILE}

                    git commit -m "Updated image to ${IMAGE_TAG} [skip ci]"

                    git push https://${GIT_USER}:${GIT_PASS}@github.com/networknuts/k8s-ai-rag-app.git HEAD:main

                    """
                }
            }
        }
    }
}
