pipeline {

    agent any

    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {

            steps {

                git branch: 'main',
                    url: 'https://github.com/networknuts/k8s-ai-rag-app.git'
            }
        }

        stage('Build and Push Docker Image') {

            steps {

                script {

                    dir('applications/rag-app/ingestor-service') {

                        def dockerImage = docker.build(
                            "docker.io/aryansr/rag-microservice-app_ingestor:${IMAGE_TAG}",
                            "."
                        )

                        docker.withRegistry('', 'dockerhub-credentials') {

                            dockerImage.push("${IMAGE_TAG}")
                        }
                    }
                }
            }
        }
    }
}
